name = "MDZ"
grammar = "markdown"
path_suffixes = ["mdz"]
line_comments = ["> "]
tab_size = 2
brackets = [
    { start = "{", end = "}", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "`", end = "`", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "[[", end = "]]", close = true, newline = false },
    { start = "{~~", end = "}", close = true, newline = false },
]
